name: Publish NuGet
description: Published NuGet

inputs:
  artifact-name:
    description: 'Artifact name containing NuGet packages to publish'
    default: 'nuget-packages'
    required: false
    type: string

runs:
  using: composite
  steps:
  - name: Download NuGet Packages
    uses: actions/download-artifact@v7
    with:
      name: ${{ inputs.artifact-name }}
      path: nuget-packages
  - name: .NET NuGet Push
    shell: bash
    run: dotnet nuget push "nuget-packages/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json