name: Build & Test

on:
  workflow_call:
    inputs:
      version:
        description: 'Image Version'
        default: '0.0.1-alpha.1'
        required: false
        type: string
      dockerfile:
        description: 'Dockerfile name'
        default: 'Dockerfile'
        required: false
        type: string
      working-directory:
        description: 'Dockerfile working directory'
        default: ''
        required: false
        type: string
      imageName:
        description: 'Image Name'
        default: 'test.loc/testimage'
        required: false
        type: string
      enableArm:
        description: 'Enables linux/arm64'
        default: true
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Save
      working-directory: ${{ inputs.working-directory }}
      run: |
        docker buildx build \
          --platform ${{ inputs.enableArm && 'linux/amd64,linux/arm64' || (runner.arch == 'ARM64' && 'linux/arm64' || 'linux/amd64') }} \
          --build-arg version=${{ inputs.version }} \
          --tag ${{ inputs.imageName }}:${{ inputs.version }} \
          --file ${{ inputs.dockerfile }} \
          --output type=oci,dest=${{ runner.temp }}/image.tar \
          .

    - name: Load
      run: |
        docker buildx build \
          --platform ${{ (runner.arch == 'ARM64' && 'linux/arm64' || 'linux/amd64') }} \
          --load \
          --build-arg version=${{ inputs.version }} \
          --tag ${{ inputs.imageName }}:${{ inputs.version }} \
          --file ${{ inputs.dockerfile }} \
          .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ inputs.imageName }}:${{ inputs.version }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      env:
        TRIVY_DISABLE_VEX_NOTICE: true

    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: testimage-oci
        path: ${{ runner.temp }}/image.tar
